---
title: "TJohnson_CaseStudy2"
author: "Terry Johnson"
date: "7/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Case Study 2 data
```{r casestudy2.2.a, include=TRUE}
### 2. Clean your Raw Data
### 2.a	Read the csv into R and take a look at the data set.Output how many rows and columns the data.frame is.

### Install package to read an Excel file
library(readxl)
### Read in the attrition data using the read_excel function
#attrition <- read_excel("/Users/stevencocke/Downloads/CaseStudy2/CaseStudy2-data.xlsx")
#setwd("C:/Users/brndn/OneDrive/Documents/Github/")
#attrition <- read_excel("Case_Study2/CaseStudy2-data.xlsx")
setwd("/Users/giovanni/")
attrition <- read_excel("CaseStudy2/CaseStudy2-data.xlsx")
### Check to make sure it is a dataframe
class(attrition)

### Look at the top lines
head(attrition,10)

### Look at the bottom lines
tail(attrition,10)

### Output the number of rows and columns in the data.frame, as well as datatypes
str(attrition)
```


```{r casestudy2.2.b, include=TRUE}
### 2.b.	The column names are either too much or not enough. Change the column names so that they do not have spaces, 
### underscores, slashes, and the like. All column names should be under 12 characters. 
### Make sure you’re updating your codebook with all information on the tidied data set as well.

### Change the column names to be under 12 characters and remove any symbols
colnames(attrition) <- c("Age", "Attrition", "BusTravel", "DailyRate", "Dept", "DistFrHme", "Education", "EducField", "EmplCnt", "EmplNum", "EnvirSatisf", "Gender", "HourlyRate", "JobInvl", "JobLvl", "JobRole", "JobSatisf", "MaritStat", "MonthlyInc", "MonthlyRte", "NumCompWrk", "Over18", "Overtime", "PercSalHike", "PerfRate", "RelatSatisf", "StnrdHrs", "StkOptLvl", "TtlWrkYrs", "TrnTmLstYr", "WrkLfBal", "YrsatComp", "YrsinCurRle", "YrsLstPromo", "YrsCurrMang")

```

```{r casestudy2.2.c, include=TRUE}
### 2.c	Some columns are, due to Qualtrics, malfunctioning.     
```


```{r casestudy2.2.d, include=TRUE}
### d	Make sure your columns are the proper data types (i.e., numeric, character, etc.).  If they are incorrect, convert them. Verify the column data etypes
str(attrition)
```


```{r casestudy2.3.a, include=TRUE}
### 3.a	Remove all observations where the participant is under age 18.  No further analysis of underage individuals is permitted by your client.  Remove any other age outliers as you see fit, but be sure to tell what you’re doing and why.
library(dplyr)
over18_attrit <- attrition %>% filter(Over18 == "Y")
head(over18_attrit)
tail(over18_attrit)
#over18_attrit$Over18

#attrition$Over18
```

```{r casestudy2.3.b, include=TRUE}
### 3.b	Please provide (in table format or similar), descriptive statistics on at least 7 variables (age, Income, etc.).  Create a simple histogram for two of them.  Comment on the shape of the distribution in your markdown.
#sapply(attrition$MonthlyInc, mean, na.rm=TRUE)  
attritYES <- attrition %>% filter( Attrition == "Yes")
attritNO  <- attrition %>% filter( Attrition == "No")

summary(attrition$MonthlyInc)
summary(attrition$Age)
summary(attrition$Education)
summary(attrition$YrsinCurRle)
summary(attrition$DistFrHme)
summary(attrition$JobLvl)
summary(attrition$PercSalHike)
hist(attrition$Age)
hist(attrition$MonthlyInc)

###We can observe that the distribution for age looks slightly normal albeit it skews slightly to the left.  This implies that the workforce is generally middle aged.  The distribution for Monthly Income skews to the left implying that most of the employees are on the lower end of the pay scale.  The employee data represents an organization that is pyramid shaped (in terms of salary compensation)

### ran additional histograms for observational purposes only, but did not necessariy rely upon the histograms that follow for any provided guidance.

hist(attritYES$PerfRate)
hist(attritNO$PerfRate)
hist(attritYES$RelatSatisf)
hist(attritNO$RelatSatisf)
hist(attritYES$WrkLfBal)
hist(attritNO$WrkLfBal)
hist(attritYES$Education)
hist(attritNO$Education)
legend("topright", inset=0.0, legend=c("1-Below College","2-College","3-Bachelor","4-Master","5-Doctor"))
hist(attritYES$EnvirSatisf)
hist(attritNO$EnvirSatisf)
hist(attritYES$JobInvl)
hist(attritNO$JobInvl)
hist(attritYES$JobSatisf)
hist(attritNO$JobSatisf)
```

```{r casestudy2.3.c, include=TRUE}
### 3.c	Give the frequencies (in table format or similar) for Gender, Education, and Occupation.  They can be separate tables, if that’s your choice.
genderCount <- data.frame(attrition %>% group_by(Gender) %>% summarise(n = n())) 
genderCount
EducCount <- data.frame(attrition %>% group_by(Education) %>% summarise(n = n())) 
EducCount
OccupCount <- data.frame(attrition %>% group_by(JobRole) %>% summarise(n = n())) 
OccupCount
```

```{r casestudy2.3.d, include=TRUE}
### 3.d	Give the counts (again, table) of management positions.
OccupCount <- data.frame(attrition %>% group_by(JobRole) %>% summarise(n = n())) 
OccupCount[4:6,]
```

```{r}

library(ggplot2)
### 4.a. Make everything visually appealing

### 4.b.	Create bar charts in ggplot or similar. The bars should be in descending order, Use any color palette of your choice other than the default.


### 4.c.	Is there a relationship between Age and Income?  Create a scatterplot and make an assessment of whether there is a relationship.  Color each point based on the Gender of the participant.  You’re welcome to use lm() or similar functions to back up your claims.
graph1 <- ggplot(attrition)
graph1 + geom_point(mapping = aes(x=Age, y=MonthlyInc, color=Gender)) +xlab("Age") + ylab("MonthlyIncome") + ggtitle ("Relationship Between Age and Monthly Income") + geom_smooth(method = "lm", mapping = aes(x=Age, y=MonthlyInc))

### Also looked at the role of job title to pay and gender. 

graph1 + geom_bar(mapping = aes(x=JobRole, y=MonthlyInc, fill=Gender), stat="identity", position = "dodge") +xlab("Job Role") + ylab("MonthlyIncome") + ggtitle ("Monthly Income by Job Role") + theme(text = element_text(size=5),axis.text.x = element_text(angle=90, hjust=1))

### utilize the objects filtered on attrition variable to run summary stats and the compare.
summary(attritYES)
summary(attritNO)
statAge <- (mean(attrition$Age)-mean(attritYES$Age))/mean(attrition$Age)
statAge1 <- (median(attrition$Age)-median(attritYES$Age))/median.default(attrition$Age)
statdis <- (mean(attrition$DistFrHme)-mean(attritYES$DistFrHme))/mean(attrition$DistFrHme)
statdis1 <- (median(attrition$DistFrHme)-median(attritYES$DistFrHme))/median.default(attrition$DistFrHme)
statenv <- (mean(attrition$EnvirSatisf)-mean(attritYES$EnvirSatisf))/mean(attrition$EnvirSatisf)
statenv1 <- (median(attrition$EnvirSatisf)-median(attritYES$EnvirSatisf))/median.default(attrition$EnvirSatisf)
statjbl <- (mean(attrition$JobLvl)-mean(attritYES$JobLvl))/mean(attrition$JobLvl)
statjbl1 <- (median(attrition$JobLvl)-median(attritYES$JobLvl))/median.default(attrition$JobLvl)
statinc <- (mean(attrition$MonthlyInc)-mean(attritYES$MonthlyInc))/mean(attrition$MonthlyInc)
statinc1 <- (median(attrition$MonthlyInc)-median(attritYES$MonthlyInc))/median.default(attrition$MonthlyInc)
statcwk <- (mean(attrition$NumCompWrk)-mean(attritYES$NumCompWrk))/mean(attrition$NumCompWrk)
statcwk1 <- (median(attrition$NumCompWrk)-median(attritYES$NumCompWrk))/median.default(attrition$NumCompWrk)
statwky <- (mean(attrition$TtlWrkYrs)-mean(attritYES$TtlWrkYrs))/mean(attrition$TtlWrkYrs)
statwky1 <- (median(attrition$TtlWrkYrs)-median(attritYES$TtlWrkYrs))/median.default(attrition$TtlWrkYrs)
statatco <- (mean(attrition$YrsatComp)-mean(attritYES$YrsatComp))/mean(attrition$YrsatComp)
statatco1 <- (median(attrition$YrsatComp)-median(attritYES$YrsatComp))/median(attrition$YrsatComp)

### Given the comparison of results, will further filter using working years (based on approx median of total sample).  
attritYESSenior <- attritYES %>% filter( TtlWrkYrs >= 11)
attritYESJunior  <- attritYES %>% filter( TtlWrkYrs <= 11)
summary(attritYESJunior)
summary(attritYESSenior)
SstatAge <- (mean(attrition$Age)-mean(attritYESSenior$Age))/mean(attrition$Age)
SstatAge1 <- (median(attrition$Age)-median(attritYESSenior$Age))/median.default(attrition$Age)
Sstatdis <- (mean(attrition$DistFrHme)-mean(attritYESSenior$DistFrHme))/mean(attrition$DistFrHme)
Sstatdis1 <- (median(attrition$DistFrHme)-median(attritYESSenior$DistFrHme))/median.default(attrition$DistFrHme)
Sstatenv <- (mean(attrition$EnvirSatisf)-mean(attritYESSenior$EnvirSatisf))/mean(attrition$EnvirSatisf)
Sstatenv1 <- (median(attrition$EnvirSatisf)-median(attritYESSenior$EnvirSatisf))/median.default(attrition$EnvirSatisf)
Sstatjbl <- (mean(attrition$JobLvl)-mean(attritYESSenior$JobLvl))/mean(attrition$JobLvl)
Sstatjbl1 <- (median(attrition$JobLvl)-median(attritYESSenior$JobLvl))/median.default(attrition$JobLvl)
Sstatinc <- (mean(attrition$MonthlyInc)-mean(attritYESSenior$MonthlyInc))/mean(attrition$MonthlyInc)
Sstatinc1 <- (median(attrition$MonthlyInc)-median(attritYESSenior$MonthlyInc))/median.default(attrition$MonthlyInc)
Sstatcwk <- (mean(attrition$NumCompWrk)-mean(attritYESSenior$NumCompWrk))/mean(attrition$NumCompWrk)
Sstatcwk1 <- (median(attrition$NumCompWrk)-median(attritYESSenior$NumCompWrk))/median.default(attrition$NumCompWrk)
Sstatwky <- (mean(attrition$TtlWrkYrs)-mean(attritYESSenior$TtlWrkYrs))/mean(attrition$TtlWrkYrs)
Sstatwky1 <- (median(attrition$TtlWrkYrs)-median(attritYESSenior$TtlWrkYrs))/median.default(attrition$TtlWrkYrs)
Sstatatco <- (mean(attrition$YrsatComp)-mean(attritYESSenior$YrsatComp))/mean(attrition$YrsatComp)
Sstatatco1 <- (median(attrition$YrsatComp)-median(attritYESSenior$YrsatComp))/median(attrition$YrsatComp)

JstatAge <- (mean(attrition$Age)-mean(attritYESJunior$Age))/mean(attrition$Age)
JstatAge1 <- (median(attrition$Age)-median(attritYESJunior$Age))/median.default(attrition$Age)
Jstatdis <- (mean(attrition$DistFrHme)-mean(attritYESJunior$DistFrHme))/mean(attrition$DistFrHme)
Jstatdis1 <- (median(attrition$DistFrHme)-median(attritYESJunior$DistFrHme))/median.default(attrition$DistFrHme)
Jstatenv <- (mean(attrition$EnvirSatisf)-mean(attritYESJunior$EnvirSatisf))/mean(attrition$EnvirSatisf)
Jstatenv1 <- (median(attrition$EnvirSatisf)-median(attritYESJunior$EnvirSatisf))/median.default(attrition$EnvirSatisf)
Jstatjbl <- (mean(attrition$JobLvl)-mean(attritYESJunior$JobLvl))/mean(attrition$JobLvl)
Jstatjbl1 <- (median(attrition$JobLvl)-median(attritYESJunior$JobLvl))/median.default(attrition$JobLvl)
Jstatinc <- (mean(attrition$MonthlyInc)-mean(attritYESJunior$MonthlyInc))/mean(attrition$MonthlyInc)
Jstatinc1 <- (median(attrition$MonthlyInc)-median(attritYESJunior$MonthlyInc))/median.default(attrition$MonthlyInc)
Jstatcwk <- (mean(attrition$NumCompWrk)-mean(attritYESJunior$NumCompWrk))/mean(attrition$NumCompWrk)
Jstatcwk1 <- (median(attrition$NumCompWrk)-median(attritYESJunior$NumCompWrk))/median.default(attrition$NumCompWrk)
Jstatwky <- (mean(attrition$TtlWrkYrs)-mean(attritYESJunior$TtlWrkYrs))/mean(attrition$TtlWrkYrs)
Jstatwky1 <- (median(attrition$TtlWrkYrs)-median(attritYESJunior$TtlWrkYrs))/median.default(attrition$TtlWrkYrs)
Jstatatco <- (mean(attrition$YrsatComp)-mean(attritYESJunior$YrsatComp))/mean(attrition$YrsatComp)
Jstatatco1 <- (median(attrition$YrsatComp)-median(attritYESJunior$YrsatComp))/median(attrition$YrsatComp)

### Consider counts for the "YES" group for the gender and Job Role variables to see if these number sku from the larger sample.

genderCount <- data.frame(attritYES %>% group_by(Gender) %>% summarise(n = n())) 
genderCount
OccupCount <- data.frame(attritYES %>% group_by(JobRole) %>% summarise(n = n())) 
OccupCount

### Some other plotting ideas based on specific job roles

### Monthly Income & attrition & job role
graph1 + geom_bar(mapping = aes(x=JobRole, y=MonthlyInc, fill=Attrition), stat="identity", position = "dodge") +xlab("Job Role") + ylab("MonthlyIncome") + ggtitle ("Monthly Income by Job Role") + theme(text = element_text(size=5),axis.text.x = element_text(angle=90, hjust=1))

### Environment Satisfactiona and Monthly Income and Attrition
graph1 + geom_point(mapping = aes(x=EnvirSatisf, y=MonthlyInc, color=Attrition)) +xlab("Environment Satisfaction") + ylab("MonthlyIncome") + ggtitle ("Relationship Between Environment and Monthly Income") 

###Consider the monthly income by level of education by job role for the "Yes" attrition group
graph2 <- ggplot(attritYES)

graph2 + geom_bar(mapping = aes(x=JobRole, y=MonthlyInc, fill=Education), stat="identity", position = "dodge") +xlab("Job Role") + ylab("MonthlyIncome") + ggtitle ("For Yes Monthly Income by Job Role by Education") + theme(text = element_text(size=5),axis.text.x = element_text(angle=90, hjust=1))

graph1 + geom_bar(mapping = aes(x=JobRole, y=MonthlyInc, fill=Education), stat="identity", position = "dodge") +xlab("Job Role") + ylab("MonthlyIncome") + ggtitle ("For Total Monthly Income by Job Role by Education") + theme(text = element_text(size=5),axis.text.x = element_text(angle=90, hjust=1))

###4.d.  What about Life Satisfaction?  Create another scatterplot.  Is there a discernible relationship there to what?   
hist(attrition$JobSatisf)
hist(attritYES$JobSatisf)
hist(attrition$RelatSatisf)
hist(attritYES$RelatSatisf)
hist(attrition$EnvirSatisf)
hist(attritYES$RelatSatisf)
hist(attritYESSenior$EnvirSatisf)
hist(attritYESJunior$JobSatisf)
hist(attritYESJunior$RelatSatisf)
hist(attritYESJunior$EnvirSatisf)
hist(attritYESSenior$JobSatisf)
hist(attritYESSenior$RelatSatisf)  
```



